### ISSUE TITLE
[lab1]关于结果的存储路径

### ISSUE THREAD

**Issue by tracer524** [Smadx/USTC-ML24-Fall#11]
实验文档中的命令使用了反斜杠来表示文件路径，例如：
`python trainC.py --results_path"..\results\train\"`
这种反斜杠（`\`）的路径分隔符仅适用于 Windows 系统，而在 Linux 和 macOS（类 UNIX 系统）中无效。

正斜杠（`/`）可以被所有现代操作系统兼容，所以建议提醒使用Linux和MacOS的同学在文件路径中使用正斜杠，如以下格式：
`python trainC.py --results_path"../results/train/"`

另外还有一点建议：如果想要保存每一次运行的结果（而不是覆盖上一次的结果），可以在`trainR.py`以及`trainC.py`中对`results_path`变量进行额外操作：
```
from utils import get_date_str
results_path = results_path / get_date_str() 
```
从而像评估结果一样每次存储在独立的文件夹中。

**Comment by Smadx** [comment]
如果要保存不同组的超参数,我们更推荐修改路径为``../results/train2/``这种方式而非使用时间戳,使用反斜杠是考虑到大多数同学都是Windows系统,
