### ISSUE TITLE
[lab1]关于预处理的问题

### ISSUE THREAD

**Issue by WingfyLyu** [Smadx/USTC-ML24-Fall#13]
助教上课是不是说了只能进行指定的那一种预处理，其他的处理都不要进行？
那如果是这样的话，实验文档中的问题1和4该如何作答？（尤其是问题1）

问题1：在对数据进行预处理时,你做了什么额外的操作,为什么？
问题4：你是否做了正则化,效果如何？为什么？

**Comment by Smadx** [comment]
对``Run_time``列只能做必要操作,其余特征可以随意处理. 
- 问题1：如果你做了额外操作,就说明为什么这样做;如果没做,就说明为什么可以不做
- 问题4：如果做了正则化就和未做正则化比较效果,并分析原因;如果没做，就说明为什么可以不做

**Comment by Daydreamfull** [comment]
是否可以预处理时去除一些相关性较低的特征？

**Comment by Smadx** [comment]
可以,你可以随意处理其余特征,但必须把操作包含在预处理函数中,以便助教对测试集做同样的处理

**Comment by WingfyLyu** [comment]
好的好的谢谢助教
