### ISSUE TITLE
[lab1]关于代码框架的疑问

### ISSUE THREAD

**Issue by ZhengWwwq** [Smadx/USTC-ML24-Fall#2]
1. 在eval_LinearRegression函数中，注释中给出的要求返回值是两个变量,$mu_pred$ 和$relative error$，但在eval_R.py的54，55行中，只接受了返回的$mu$
![image](https://github.com/user-attachments/assets/8fbbe9dd-cb08-4b03-a3af-ff0892fc477d)
![image](https://github.com/user-attachments/assets/8808d18c-35e2-47a0-a2a1-7b7a2939b899)

2.在utils.py的DataLoader类中的__next__方法中，在train模式下，似乎没有raise StopIteration（那行注释是我自己加的），这样就会在for batch in self.train_loader时，无限循环（可以通过加一层判断来终止）
![image](https://github.com/user-attachments/assets/4e51a856-d6d8-4f31-95dc-3715fa19fbe1)

**Comment by Smadx** [comment]
## 1
已修复,请同步仓库
## 2
这里在``train``模式下``Dataloader``会无限循环是因为我们使用训练步数来控制迭代,而不是epoch-batch模式,请检查``TrainerR.train()``的``while``循环条件,不必使用下面的语句:
```python
for batch in self.train_loader:
```
请直接使用``Dataloader``的``next``方法
