### ISSUE TITLE
[lab1]关于mean的选取

### ISSUE THREAD

**Issue by Hrc22** [Smadx/USTC-ML24-Fall#24]
要求中使用lab1中的预测mean结果作为lab2中的分类依据mean，但是lab1对数据集进行了shuffle操作，导致两个lab对应的test集并不一样，这样mean的误差较大

**Comment by Smadx** [comment]
数据分布比较稳定,一般``mean``差距不大,并且最终提交后我们要在测试集上测试,测试集的均值和你拿到的数据也有少许差异,这种情况是无法避免的

**Comment by Hrc22** [comment]
那合理的做法不应该是先用lab1来预测我需要分类的数据集的均值，在用这个均值进行分类。
