### ISSUE TITLE
[lab1]程序一直在`for batch in self.train_loader:`死循环怎么办

### ISSUE THREAD

**Issue by woqinmian** [Smadx/USTC-ML24-Fall#30]
默认参数未进行任何修改

**Comment by Smadx** [comment]
#2

**Comment by woqinmian** [comment]
在1.6所写的`eval_LinearRegression(model: LinearRegression, loader: DataLoader)`方法中，为什么使用`for batch in loader:`可以跳出该循环

**Comment by Smadx** [comment]
只有当``Dataloader``的``train``为``True``时才会无限循环
