### ISSUE TITLE
[lab1]关于分类任务的问题

### ISSUE THREAD

**Issue by Luwenbo001** [Smadx/USTC-ML24-Fall#32]
我在完成分类任务时出现了loss快速下降，然后陷入一个定值的状况。在此状态下，ACC也为定值。我多次调整学习率、学习率降低速度等参数，但loss最后仍会下降为一个定值。 我猜测这可能是因为局部最优解的原因。 请问除了局部最优解外。还有可能是什么因素导致了loss每次都会降低为一个定值？ 我该做什么去进一步降低我的loss提高我的ACC？

**Comment by Smadx** [comment]
使用整个数据集的数据做梯度下降时的训练过程会很稳定，另外,这是一个凸优化问题,如果你的loss和acc是定值很可能已经达到了全局最优解。

当然,你也可以试试用``sklearn``库acc可以达到多少,如果和你的结果差距较大可能是你前面的实现有些问题
