### ISSUE TITLE
[lab1]关于shape不匹配

### ISSUE THREAD

**Issue by htianmeng** [Smadx/USTC-ML24-Fall#33]
grad_w需要匹配的是(14,1)但是它是(14,4096)如何处理这个不匹配问题（grad_b也是这样）
<img width="663" alt="image" src="https://github.com/user-attachments/assets/7e066884-2121-481c-a46f-54274107bc3e">
<img width="656" alt="image" src="https://github.com/user-attachments/assets/0fb256f1-6d59-4ea9-a861-25b2adc82774">

**Comment by ivcylc** [comment]
啊，我觉得是你 grad_w 算错了，grad_w 里 bs 这个维度是要随着和 W 做乘法自动消失了吧？
