### ISSUE TITLE
[lab1]调参效果不佳

### ISSUE THREAD

**Issue by ViXiC-36** [Smadx/USTC-ML24-Fall#34]
在线性回归部分的调参过程中，本人的loss下降到1左右后几乎无法再优化，得到的relative error却比较不理想（大于3%），并且通过计算决策系数$R^2$发现一直处于-1和0之间，而这几乎无法通过调参来解决，请问是否应该检查代码（预处理？初始化？），还是继续调参？
另外，本人的参数初始化全部使用了0
![Screenshot 2024-10-07 134803](https://github.com/user-attachments/assets/d0a5d76f-97ca-469e-bf4b-d8d8e4ea7692)
![image](https://github.com/user-attachments/assets/da9df7c3-3274-4e5d-8c02-0a2d5a5c6277)

**Comment by ViXiC-36** [comment]
另外在测试集上运行eval.py得到的结果与在验证集上的结果没有显著差别

**Comment by Smadx** [comment]
> 在线性回归部分的调参过程中，本人的loss下降到1左右后几乎无法再优化，得到的relative error却比较不理想（大于3%），并且通过计算决策系数$R^2$发现一直处于-1和0之间，而这几乎无法通过调参来解决，请问是否应该检查代码（预处理？初始化？），还是继续调参？ 另外，本人的参数初始化全部使用了0 ![Screenshot 2024-10-07 134803](https://private-user-images.githubusercontent.com/157372574/374045509-d0a5d76f-97ca-469e-bf4b-d8d8e4ea7692.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyODA3NjEsIm5iZiI6MTcyODI4MDQ2MSwicGF0aCI6Ii8xNTczNzI1NzQvMzc0MDQ1NTA5LWQwYTVkNzZmLTk3Y2EtNDY5ZS1iZjRiLWQ4ZDhlNGVhNzY5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwNTU0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmEwZTFjNzQ5MjlkNzcwZTlkMWQ5NTVkYzA3ZTJmODlkZDg3ZWQ5N2ExZDNhY2UwODBhZGNkZjQ4YzM5NjRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IX1kH1a09Ju_9CV2mgNxk-O-m2H2gsiusBiUB30_1gU) ![image](https://private-user-images.githubusercontent.com/157372574/374045765-da9df7c3-3274-4e5d-8c02-0a2d5a5c6277.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyODA3NjEsIm5iZiI6MTcyODI4MDQ2MSwicGF0aCI6Ii8xNTczNzI1NzQvMzc0MDQ1NzY1LWRhOWRmN2MzLTMyNzQtNGU1ZC04YzAyLTBhMmQ1YTVjNjI3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwNTU0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODQ2NmI2NDc5YWZmMjk1NWU3NTlmZDc2YjY2OTk2OTA4MDllMzg4NzVhMWE5MzhlNmE2Yjc1NjRjMDQ4YmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GMwFzFc81hGZxpAO82y4e2afghleABQ2TmEpJJNBWaU)

对数据做归一化之后再调参效果会好一些,

> 另外在测试集上运行eval.py得到的结果与在验证集上的结果没有显著差别

这是正常的
