### ISSUE TITLE
[lab1]第二部分loss为0，accuracy为1该怎么反思

### ISSUE THREAD

**Issue by woqinmian** [Smadx/USTC-ML24-Fall#35]
![loss_list](https://github.com/user-attachments/assets/43af0fe1-f766-44bd-a073-2a3c97407086)

**Comment by Smadx** [comment]
可能你没对分类问题的``Run_time``列取对数,导致所有样本的``label``都是1

**Comment by woqinmian** [comment]
增大训练的步数，发现loss趋近于0.5，该怎么解决

**Comment by Smadx** [comment]
#32
