### ISSUE TITLE
[lab1]想请问第一部分训练loss震动幅度过大怎么办

### ISSUE THREAD

**Issue by ivcylc** [Smadx/USTC-ML24-Fall#36]
虽然指标不错，但是感觉不是正常现象，学习率已经足够低
<img width="537" alt="截屏2024-10-07 15 00 38" src="https://github.com/user-attachments/assets/b2deca83-c8d2-4af5-9b05-66075ce2262d">

**Comment by Smadx** [comment]
这是正常现象
