### ISSUE TITLE
[lab1]为什么Classification部分注释里Args写的是train_loader，但后面改为dataset

### ISSUE THREAD

**Issue by jonsank** [Smadx/USTC-ML24-Fall#39]
![屏幕截图 2024-10-09 213039](https://github.com/user-attachments/assets/48329e7e-1627-4455-be88-62f4264d5ade)
如图，前面Regression部分用的是dataloader,Classification部分却和注释里的不同。

**Comment by Smadx** [comment]
注释忘记改了,因为Classification部分不用``Dataloader``

**Comment by Smadx** [comment]
另外注意这里dataset的类型是``np.ndarray``而不是``Dataset``
