### ISSUE TITLE
[lab1]关于第一部分运行不了的一点疑问

### ISSUE THREAD

**Issue by Minrui1Zhang** [Smadx/USTC-ML24-Fall#41]
本人写好第一步部分代码后尝试运行，结果如下：
![TTTT](https://github.com/user-attachments/assets/e18328c1-3422-407d-a2a8-7961c7d93bed)
这是前面数据集预处理和划分出了问题吗？
之前的def trainR函数忘保存了，后面调整如下，老是出现这样的问题：
![image](https://github.com/user-attachments/assets/459bce9b-f588-479e-a6d4-0054f6f48f66)
这个划红线的地方无论有没有，运行时都会报错。
![image](https://github.com/user-attachments/assets/b7bc8074-b6dc-4c5c-a383-363973766d20)

**Comment by Smadx** [comment]
你是不是修改了``Loss``类型的定义,``__call__``方法应该只接收两个参数啊

**Comment by Minrui1Zhang** [comment]
![image](https://github.com/user-attachments/assets/3b45fe7a-9d0c-42b7-bc3e-55bc93a94002)
这倒没有修改

**Comment by Minrui1Zhang** [comment]
loss和backwards分别只接受2、3个参数时又出现这样的问题
![image](https://github.com/user-attachments/assets/d47b9c28-a41e-48d8-9575-3641634b99b7)

**Comment by Smadx** [comment]
看看model定义
