### ISSUE TITLE
[lab2] 关于优化与评分标准

### ISSUE THREAD

**Issue by HenRiser** [Smadx/USTC-ML24-Fall#49]
请问lab2的两个部分都是要优化到什么程度啊，我现在做了第一部分，loss在0.05上下，但准确率会在0.3到0.8这段大波动，可能是跟shuffle=True有关
![屏幕截图 2024-10-28 220338](https://github.com/user-attachments/assets/27477ca3-754d-4395-b5ec-32fb31cb906b)
目前调的参数有alpha和lr_init，我是否还需要从solver，activation等参数下手
谢谢

**Comment by Smadx** [comment]
@Sakura-Walker

**Comment by Sakura-Walker** [comment]
是的，可以更改一下激活函数

**Comment by HenRiser** [comment]
问题出在对X_train标准化后训练模型时还是用的X_train而不是standard_train,而在acc评估中用的是standard_test，所以最终算出来的会有很大偏差
