### ISSUE TITLE
[lab2]关于数据集以及评分标准

### ISSUE THREAD

**Issue by LZFXDD** [Smadx/USTC-ML24-Fall#52]
iris数据集也太小了吧......
我的模型没有进行任何调参就能做到1的accuracy，想问一下这个数据集是不是不太合适
以及这个评分标准有点太模糊了，手动实现神经网络这部分的代码有60分，但只有四个很容易实现的函数？而且神经网络也只有一个hidden layer......

**Comment by Smadx** [comment]
是不是这个实验太温柔了同学有点不习惯了

**Comment by Smadx** [comment]
@Sakura-Walker

**Comment by LZFXDD** [comment]
这个实验有额外的不公开的测试集吗
如果没有的话那降低loss是为了啥......

**Comment by Sakura-Walker** [comment]
本实验无额外的数据集，因为IRIS数据集比较简单，所以说epoch和隐藏层数不需要设置太高就能达到预期效果了。本实验设置的相对简单，需要考虑到有些同学初次接触编程。有余力的同学可以加一些可视化。
