### ISSUE TITLE
[lab1]关于第一部分拟合对象，拟合效果，以及暗数据的一些疑问

### ISSUE THREAD

**Issue by MSEloss** [Smadx/USTC-ML24-Fall#6]
1. 拟合是不是应当对原数据拟合，而非对处理过后的数据拟合，即输出是否应当exp回去？
2. 对于均值的拟合效果往往与最小化MSELoss不太一致，在我尽量最小化处理后数据的MSELoss之后，还原成原数据的均值往往偏小，而一个MSEloss较大的函数，比如说常值函数却可以起到更好的效果。
3. 在我尝试很多处理后拟合效果仍不理想，在优化MSELoss的同时测评分数却不断下降（也有可能是MSELoss不够小），但是很多拟合效果非常差的方法可以在测评中得到满分，我对于如此简单的模型能否产生一个很成功的拟合产生了疑惑，请问能否给出一个成功拟合的（predict ,target）图表范例？
4. 暗数据是否是随机选取？

**Comment by MSEloss** [comment]
主要是调参调不出来，想看一下比较好的拟合图

**Comment by Smadx** [comment]
## 1
拟合是对处理后的数据拟合
## 2
使用相对误差作为评分标准其实是为了计分方便(因为使用不同的预处理得到的MSE数量级差异较大),我们希望同学在训练时的主要目标是最小化MSE,均值主要是作为分类问题的基准使用.
## 3
数据分布是非常好的,MSE可以优化到一个很小的数值,你可以在notebook中对数据分布做一定的分析发现这一点. 对于你说的拟合效果很差却得到了不错的测评分数,这其实是降低了难度,我们在计算相对误差时使用: 
```python
np.abs(pred.mean()-target.mean())/target.mean()
```
而不是
```python
np.abs(pred-target).mean()/target.mean()
```
你可以试试用下面这种方式计算相对误差,评测分数大概率会降低不少.
我们还是希望大家正常按照最小化MSE的思路调参优化模型,把相对误差只是当做一个副产品,也没必要硬卷Performance分数
## 4
测试集数据分布与助教提供的数据集分布几乎一致,在最终测评时性能差异不会很大.

**Comment by MSEloss** [comment]
我第一个问题有点问错了，我的意思是评分时数据是否需要还原，虽然如果效果真的很好就不用问了。

**Comment by MSEloss** [comment]
我在仅取对数时将MSEloss降低到了0.4便难以继续，然而这个结果将只能获得0分，以下是我对于对数的拟合结果，
<img width="432" alt="ex" src="https://github.com/user-attachments/assets/a7bce838-93c3-4e4e-b838-4db65e096744">
请问能否给出正确的MSEloss以及成功的结果

**Comment by MSEloss** [comment]
我已经用上了我可以想到的所有方法，结果一分没有，有点难以接受

**Comment by MSEloss** [comment]
上面这个表横坐标是预测，纵坐标是实际值

**Comment by Smadx** [comment]
评分时数据无需还原,你对数据做的任何预处理必须包含在``data_preprocessing_regression``函数中,这样评分时助教会调用这个函数对测试集做同样的预处理. 
助教在只取对数时MSE优化到个位数左右就有不错的效果,如果你觉得这样性能不行,还是试试在预处理阶段加点归一化吧,如果只取对数调参确实相对困难一些

**Comment by Smadx** [comment]
只取对数,用默认参数跑出来大概长这样:
![loss_list](https://github.com/user-attachments/assets/f6d60495-6605-4788-bbdd-3deed3d2d6d8)

**Comment by MSEloss** [comment]
无需还原的话有个问题，如果将所有数值一起增加固定值，那不是无论怎么测量相对误差都很小了吗？比如原本数据1预测2，做处理x=x+100000，处理完变成100001和100002相对误差就减少了约100000倍

**Comment by MSEloss** [comment]
事实上我已经对参数归一化，并添加了动量等优化方法，然而模型仍然不是很好，可以看到预测值与实际值总是无法吻合的很好，

**Comment by MSEloss** [comment]
我感觉是参数量太少了

**Comment by MSEloss** [comment]
我两天前就已经把MSEloss优化到1以内了，但是还原后效果非常差，注意到分类问题高度依赖本问题，我花费了两天时间优化它，但是仍然不是很理想,我觉得本题使用简单的线性回归问题非常大。

**Comment by Smadx** [comment]
## 对数据预处理和调参问题的说明
> 无需还原的话有个问题，如果将所有数值一起增加固定值，那不是无论怎么测量相对误差都很小了吗？比如原本数据1预测2，做处理x=x+100000，处理完变成100001和100002相对误差就减少了约100000倍

确实是这样的,可是这种处理有什么实际意义？无非是提升点指标.稍后我会补充一些预处理要求,请同学记得查看.


> 事实上我已经对参数归一化，并添加了动量等优化方法，然而模型仍然不是很好，可以看到预测值与实际值总是无法吻合的很好，

优化方法不需要很复杂,这个线性回归问题没那么难,可以先调整``batch_size``和``lr``这两个参数. 


## 对线性回归问题的说明
线性回归可以很好的解决本问题,效果较差可能是模型优化不到位,你可以在notebook中分析数据,可以得出有特征对``run_time``有很强的线性相关性,如果你还是有所怀疑,请私聊助教说明你是如何实现的
