### ISSUE TITLE
[lab3]执行grade.py时出错

### ISSUE THREAD

**Issue by ViXiC-36** [Smadx/USTC-ML24-Fall#68]
执行grade.py时遇到以下报错
![image](https://github.com/user-attachments/assets/64e406b8-e1dd-46b5-8a7f-5268656fde31)
经过检查后发现，e_step函数中传入的self.covs矩阵的元素全部为NaN，但是self不是在init处就定义好了吗，请问为什么会这样？

**Comment by Smadx** [comment]
说明保存的参数文件里``covs``的元素全为NaN
