### ISSUE TITLE
[lab1]关于跑实验的问题

### ISSUE THREAD

**Issue by WingfyLyu** [Smadx/USTC-ML24-Fall#9]
助教助教，实验跑的太慢了（属于要跑几个小时的那种），但是Loss确实在及其缓慢地降低，这种一般是出了什么问题？可以给点建议吗T_T

**Comment by Smadx** [comment]
跑太慢了应该是你把epoch设置的太大了,如果觉得loss下降太慢可以调大学习率

**Comment by WingfyLyu** [comment]
我是按照助教默认的参数跑的，是不是我模型写的就有问题？

**Comment by Smadx** [comment]
那可能你写的确实有问题

**Comment by WingfyLyu** [comment]
助教，按初始参数训练，训练过程中线性回归的loss大概是从多少降到多少？我想有个大概的预期值

**Comment by Smadx** [comment]
请查看 #6
